### ISSUE TITLE
`node-pre-gyp install --fallback-to-build` npm ERR! Exit status 1

### ISSUE THREAD

**Issue by marconealberto** [EmergingTechnologyAdvisors/node-serialport#1089]
I've seen people posting similar errors, not sure if this is a duplicate or not.
I'ts happening on a fresh install of a RASPBIAN JESSIE LITE.

```
pi@raspberrypi:~ $ sudo npm i serialport@4.0.6
\
> serialport@4.0.6 install /home/pi/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.6/serialport-v4.0.6-node-v46-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.6 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node_modules/serialport/.node-gyp"
make: Entering directory '/home/pi/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/4.2.6/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/pi/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/home/pi/node_modules/serialport/build/Release"
gyp ERR! cwd /home/pi/node_modules/serialport
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

```

node -v
v4.2.6

npm -v
4.0.5

Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux

**Comment by fivdi** [comment]
Please take a look at the [installation instructions](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/master/README.md#sudo--root).
