### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 51.

### ISSUE THREAD

**Issue by humblewizard** [EmergingTechnologyAdvisors/node-serialport#1181]
OS: Ubuntu 14.04
Nodejs: 6.10.3
Serialport: What I got with "npm install serialport"

I have a module that used to work but I've upgraded from node v0.1 to 6.10.3  I did remove the old version first and deleted the node_modules and reinstalled serialport after nodejs. But now I have this error:

```
Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/bob/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/bob/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (module.js:570:32)
```
I've removed node and is modules directory and started over. It maybe one of the other modules I'm loading. It is this next line that is causing the fault:

```
var com = require("serialport");
```

Edit...I get a different version for 

$ node -v 
v7.10

**Comment by humblewizard** [comment]
Deleting the 7.10 version and reinstalling serialport fixed this issue. Don't know how that got installed.
