### ISSUE TITLE
Not a valid Win32 Application

### ISSUE THREAD

**Issue by Craytor** [EmergingTechnologyAdvisors/node-serialport#1274]
SerialPort Version: 5.0.0
NodeJS: 8
OS: Windows 10 / MacOS Sierra

### Summary of Problem
First and foremost, this is an amazing library. When I go to build my Electron app for production for Mac, and I run it, it works great. For windows, the app builds, but when I go to run it I get the following error.

Also, I'm building both on MacOS.

```
C:\Users\Tyler Youschak\AppData\Local\Programs\gps-app\resources\app.asar\node_modules\serialport\node_modules\bindings\bindings.js:88 Uncaught Error: %1 is not a valid Win32 application.
\\?\C:\Users\Tyler Youschak\AppData\Local\Temp\1F6E.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\Tyler Youschak\AppData\Local\Programs\gps-app\resources\app.asar\node_modules\serialport\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Users\Tyler Youschak\AppData\Local\Programs\gps-app\resources\app.asar\node_modules\serialport\lib\bindings\win32.js:2:36)
```

### Steps and Code to Reproduce the Issue
```npm run build``` with ```SimulatedGREG/electron-vue```.

**Comment by Craytor** [comment]
Had to rebuild and that solved issues.
