### ISSUE TITLE
Installation issues on ARM Cortex M4 yocto linux build

### ISSUE THREAD

**Issue by markmitton** [EmergingTechnologyAdvisors/node-serialport#1290]
serialport: v5.1.0-beta5
node: v6.10.3
npm: v3.10.10
os: linux 4.4.68 (Yocto linux project)
hw: see below

processor	: 0
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 351.43
Features	: half thumb fastmult vfp edsp vfpv3 vfpv3d16 tls vfpv4 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc05
CPU revision	: 1
Hardware	: Atmel SAMA5

I have tried installing using npm as user/root and with/without flags --unsafe-perm and --build-from-source without success.

The following output  is from executing as follows:
sudo npm install -g serialport --unsafe-perm --build-from-source

Can you anyone please point me in the direction as to why npm can't build this package or what it is complaining about?

sudo npm install -g serialport --unsafe-perm --build-from-source
/usr/bin/serialport-list -> /usr/lib/node_modules/serialport/bin/list.js
/usr/bin/serialport-repl -> /usr/lib/node_modules/serialport/bin/repl.js
/usr/bin/serialport-term -> /usr/lib/node_modules/serialport/bin/terminal.js

> serialport@5.0.0 install /usr/lib/node_modules/serialport
> node-pre-gyp install --fallback-to-build

make: Entering directory '/usr/lib/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
g++: error trying to exec 'as': execvp: No such file or directory
make: *** [serialport.target.mk:94: Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory '/usr/lib/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.68_figcomp2-01701-gfa8486c
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/usr/lib/node_modules/serialport/build/Release"
gyp ERR! cwd /usr/lib/node_modules/serialport
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/lib/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.68_figcomp2-01701-gfa8486c
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/serialport
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/usr/lib/node_modules/serialport/build/Release' (1)
npm ERR! Linux 4.4.68_figcomp2-01701-gfa8486c
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "serialport" "--unsafe-perm" "--build-from-source"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! serialport@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@5.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/root/npm-debug.log

**Comment by markmitton** [comment]
OK so seems to have been a problem with the toolchain. Reinstalled and it now builds node-serialport.
